status = [
  "buildkite/thermodynamics-ci",
  "ci 1.6 - ubuntu-latest",
  "ci 1.6 - windows-latest",
  "ci 1.6 - macOS-latest",
  "ci 1.7 - ubuntu-latest",
  "ci 1.7 - windows-latest",
  "ci 1.7 - macOS-latest",
  "ci 1.8 - ubuntu-latest",
  "ci 1.8 - windows-latest",
  "ci 1.8 - macOS-latest",
  "docbuild",
  "format",
]
delete_merged_branches = true
timeout_sec = 10800
block_labels = [ "do-not-merge-yet" ]
cut_body_after = "<!--"
