agents:
  queue: central
  slurm_mem: 8G
  modules: climacommon/2025_03_18

env:
  JULIA_LOAD_PATH: "${JULIA_LOAD_PATH}:${BUILDKITE_BUILD_CHECKOUT_PATH}/.buildkite"
  OPENBLAS_NUM_THREADS: 1
  JULIA_NVTX_CALLBACKS: gc
  OMPI_MCA_opal_warn_on_missing_libcuda: 0
  JULIA_MAX_NUM_PRECOMPILE_FILES: 100
  JULIA_DEPOT_PATH: "${BUILDKITE_BUILD_PATH}/${BUILDKITE_PIPELINE_SLUG}/depot/default"

steps:
  - label: "init env"
    key: "init_env"
    concurrency: 1
    concurrency_group: 'depot/thermodynamics-ci'
    command:
      - "echo $JULIA_DEPOT_PATH"
      - "julia --project=test -e 'using Pkg; Pkg.instantiate(;verbose=true)'"
      - "julia --project=test -e 'using Pkg; Pkg.develop(path=\".\"); Pkg.instantiate(;verbose=true); Pkg.precompile()'"
      - "julia --project=test -e 'using CUDA; CUDA.precompile_runtime()'"
      - "julia --project=test -e 'using Pkg; Pkg.status()'"
    agents:
      slurm_ntasks: 1
      slurm_gpus: 1

  - wait

  - label: "CPU tests"
    command:
      - "THERMODYNAMICS_INCLUDE_DEPRECATED=false julia --project=test --color=yes test/runtests.jl"
    agents:
      slurm_ntasks: 1
    timeout_in_minutes: 60

  - label: "GPU tests"
    command:
      - "julia --project=test --color=yes test/runtests_gpu.jl"
    agents:
      slurm_ntasks: 1
      slurm_gpus: 1
    timeout_in_minutes: 60

