agents:
  queue: central
  slurm_mem: 8G
  modules: julia/1.9.3 cuda/12.2

env:
  JULIA_VERSION: "1.9.3"
  OPENBLAS_NUM_THREADS: 1
  CUDA_VERSION: "12.2"
  OMPI_MCA_opal_warn_on_missing_libcuda: 0
  JULIA_CPU_TARGET: 'broadwell;skylake'

steps:
  - label: "init environment :computer:"
    key: "init_env"
    command:
      - echo "--- Instantiate test env"
      - julia --project=test -e 'using Pkg; Pkg.develop(path="."); Pkg.instantiate(;verbose=true); Pkg.precompile(;strict=true); Pkg.status()'

      - echo "--- Instantiate perf env"
      - julia --project=perf -e 'using Pkg; Pkg.develop(path="."); Pkg.instantiate(;verbose=true); Pkg.precompile(;strict=true); Pkg.status()'

      - echo "--- Instantiate gpu env"
      - julia --project=gpuenv -e 'using Pkg; Pkg.develop(path="."); Pkg.instantiate(;verbose=true); Pkg.precompile(;strict=true); using CUDA; CUDA.precompile_runtime(); Pkg.status()'
    agents:
      slurm_ntasks: 1
      slurm_gpus: 1

  - wait

  - label: "CPU tests"
    command:
      - "julia --project=test test/runtests.jl"
    agents:
      slurm_ntasks: 1
    timeout_in_minutes: 60

  - label: ":scales: Allocation monitoring"
    command:
      - "julia --project=perf perf/allocs.jl"
    artifact_paths:
      - "perf/allocations_output/*"
    agents:
      slurm_ntasks: 1
    timeout_in_minutes: 60

  - label: ":mag::rocket: Constructor benchmarks"
    command:
      - "julia --project=perf perf/benchmark.jl"
    agents:
      slurm_ntasks: 1
    timeout_in_minutes: 60

  - label: ":mag::rocket: Constructor micro-benchmarks"
    command:
      - "julia --project=perf perf/microbenchmarks.jl"
    agents:
      slurm_ntasks: 1
    timeout_in_minutes: 60

  - label: ":mag::rocket: Constructor flop measurements"
    command:
      - "julia --project=perf perf/flops.jl"
    agents:
      slurm_ntasks: 1
    timeout_in_minutes: 60

  - label: ":mag::rocket: JET tests"
    command:
      - "julia --project=perf perf/jet.jl"
    agents:
      slurm_ntasks: 1
    timeout_in_minutes: 60

  - label: "KernelAbstraction GPU tests"
    command:
      - "julia --project=gpuenv test/runtests_gpu.jl CuArray"
    agents:
      slurm_ntasks: 1
      slurm_gpus: 1
    timeout_in_minutes: 60

  - label: "KernelAbstraction CPU tests"
    command:
      - "julia --project=gpuenv test/runtests_gpu.jl"
    agents:
      slurm_ntasks: 1
      slurm_gpus: 1
    timeout_in_minutes: 60
